"""Add external_userid and user_type to users table

Revision ID: 6c9fab89033a
Revises: 
Create Date: 2025-11-19 21:40:08.400989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = '6c9fab89033a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.String(length=256), nullable=False, comment='搜索关键词'),
    sa.Column('platform', sa.String(length=32), nullable=False, comment='平台名称'),
    sa.Column('product_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='商品详情JSON'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='价格'),
    sa.Column('url', sa.Text(), nullable=False, comment='商品链接'),
    sa.Column('cached_at', sa.DateTime(), nullable=False, comment='缓存时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_cache_expires_at'), 'product_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_product_cache_platform'), 'product_cache', ['platform'], unique=False)
    op.create_index(op.f('ix_product_cache_search_query'), 'product_cache', ['search_query'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wecom_user_id', sa.String(length=128), nullable=True, comment='企业微信用户ID（普通应用）'),
    sa.Column('external_userid', sa.String(length=128), nullable=True, comment='外部用户ID（客服应用）'),
    sa.Column('nickname', sa.String(length=128), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='头像URL'),
    sa.Column('user_type', sa.String(length=32), nullable=False, comment='用户类型: internal=内部员工, external=外部客户'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_external_userid'), 'users', ['external_userid'], unique=True)
    op.create_index(op.f('ix_users_wecom_user_id'), 'users', ['wecom_user_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False, comment='会话ID'),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False, comment='角色：用户/助手'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('intent', sa.String(length=64), nullable=True, comment='识别的意图'),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='提取的实体'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SUPPLY', 'DEMAND', name='servicetype'), nullable=False, comment='服务类型：供应/需求'),
    sa.Column('category', sa.String(length=128), nullable=True, comment='服务分类'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='标题'),
    sa.Column('description', sa.Text(), nullable=False, comment='详细描述'),
    sa.Column('price_range', sa.String(length=64), nullable=True, comment='价格区间'),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='联系方式'),
    sa.Column('embedding', Vector(dim=1536), nullable=True, comment='向量embeddings'),
    sa.Column('status', sa.Enum('ACTIVE', 'MATCHED', 'CLOSED', name='servicestatus'), nullable=False, comment='状态'),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True, comment='标签数组'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('expired_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_created_at'), 'services', ['created_at'], unique=False)
    op.create_index(op.f('ix_services_status'), 'services', ['status'], unique=False)
    op.create_index(op.f('ix_services_type'), 'services', ['type'], unique=False)
    op.create_index(op.f('ix_services_user_id'), 'services', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supply_id', sa.UUID(), nullable=False, comment='供应服务ID'),
    sa.Column('demand_id', sa.UUID(), nullable=False, comment='需求服务ID'),
    sa.Column('similarity_score', sa.Float(), nullable=False, comment='相似度分数'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='matchstatus'), nullable=False, comment='匹配状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['demand_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supply_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_demand_id'), 'matches', ['demand_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_supply_id'), 'matches', ['supply_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_supply_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_demand_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_services_user_id'), table_name='services')
    op.drop_index(op.f('ix_services_type'), table_name='services')
    op.drop_index(op.f('ix_services_status'), table_name='services')
    op.drop_index(op.f('ix_services_created_at'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_wecom_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_userid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_product_cache_search_query'), table_name='product_cache')
    op.drop_index(op.f('ix_product_cache_platform'), table_name='product_cache')
    op.drop_index(op.f('ix_product_cache_expires_at'), table_name='product_cache')
    op.drop_table('product_cache')
    # ### end Alembic commands ###

